<?php

/**
 * @file
 * Functions to support theming in the Tailwind CSS theme.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_preprocess_HOOK().
 */
function tailwindcss_preprocess_block(&$variables) {
  if (tailwindcss_get_active_theme() == 'tailwindcss' && $variables['base_plugin_id'] == 'system_branding_block') {
    $variables['site_logo'] = '';
    if ($variables['content']['site_logo']['#access'] && $variables['content']['site_logo']['#uri']) {
      $variables['site_logo'] = str_replace('.svg', '.png', $variables['content']['site_logo']['#uri']);
    }
  }
}


/**
 * Get the active theme.
 *
 * @return string
 *   The name of the active theme.
 */
function kinasevych_dev_get_active_theme() {
  return \Drupal::service('theme.manager')->getActiveTheme()->getName();
}

/**
 * Implements hook_preprocess_page.
 *
 * @param $variables
 *
 */

function kinasevych_dev_preprocess_page(&$variables) {
  // Pass site name.
  $variables['site_name'] = \Drupal::config('system.site')->get('name');

  // Pass site slogan.
  $variables['site_slogan'] = \Drupal::config('system.site')->get('slogan');

  // Pass langcode.
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['language'] = $language;

  // Pass logo path.
  $variables['logopath'] = file_url_transform_relative(file_create_url(theme_get_setting('logo.url')));
}


/**
 * Preprocess variables for html templates.
 */
function kinasevych_dev_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $current_path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  $path_class = $current_path_alias == '/home' ? 'path-frontpage' : 'path' . Html::getClass($current_path_alias);
  if (isset($path_class)) {
    $variables['attributes']['class'][] = $path_class;
  }
}
